name: Continous Integration

on:
  push:
    branches:
      - 'source'
  pull_request:

permissions:
  contents: write

jobs:
  build:
    name: 'Build 📦'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['25.8.2']

    steps:
      - name: Checking out the latest code
        uses: actions/checkout@v4

      - name: Setting up nodejs for building codebase and Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable corepack and pnpm
        run: corepack enable && corepack prepare pnpm@9.15.0 --activate && pnpm -v

      - name: Installing Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

  dependabot:
      name: 'Dependabot'
      needs: [build] # After the build job, if it fails, it won't merge the PR.
      runs-on: ubuntu-latest
      if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}} # Detect that the PR author is dependabot
      steps:
        - name: Enable auto-merge for Dependabot PRs
          run: gh pr merge --auto --merge "$PR_URL" # Use Github CLI to merge automatically the PR
          env:
            PR_URL: ${{github.event.pull_request.html_url}}
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}